### PR TITLE
Fix for issue #41

### PR DESCRIPTION
**Pull request by peteruithoven**

### CODE REVIEW

**Comment by JohnMcLear** [comment]
FWIW @fourplusone  isn't publishing these plugins so it's probable this wont land in NPM

**Comment by peteruithoven** [comment]
@fourplusone, I would gladly take on that responsibility. Could you add me as a user on npm? I hope that that allows me to publish changes. See: https://docs.npmjs.com/cli/owner 
I would like to prevent having to publish it as something like _linkify2_. 

I would also like to put linkify in it's own repository, just like [headings2](https://www.npmjs.com/package/ep_headings2). (Probably I would create that repository as a fork of this one, to keep the git history intact.)

**Comment by fourplusone** [comment]
@JohnMcLear @peteruithoven whats your username at npm?

**Comment by JohnMcLear** [comment]
https://www.npmjs.com/~johnyma22

**Comment by fourplusone** [comment]
added you as a repo owner. thanks for keep these plugins up to date :)

**Comment by peteruithoven** [comment]
https://www.npmjs.com/~peteruithoven

**Comment by rugk** [comment]
Any news?

**Comment by JohnMcLear** [comment]
Need to bump @fourplusone

**Pull request merged**
